name: Setup Node
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: ./frontend/package.json
    - uses: actions/setup-node@v4
      with:
        node-version-file: ./frontend/.node-version
        cache: pnpm
        cache-dependency-path: "./frontend/pnpm-lock.yaml"
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
      shell: bash
      working-directory: frontend
