name: Frontend CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'frontend/**'
      - 'backend/openapi.yaml'
      - '.github/workflows/frontend-ci.yaml'
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run linter
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run test
        run: pnpm test
