name: Terraform apply

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
    branches:
      - main

jobs:
  exec:
    strategy:
      matrix:
        env: [dev, prod]
    environment: ${{ matrix.env }}
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      TERRAFORM_DIR: terraform/environments/${{ matrix.env }}
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0.8.0
        with:
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/deepfake-github-wip/providers/deepfake-oidc-provider
          service_account: deepfake-wip-user@deepfake-${{ matrix.env }}.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v2

      - run: cd "$TERRAFORM_DIR"; terraform fmt -check -recursive
      - run: cd "$TERRAFORM_DIR"; terraform init
      - run: cd "$TERRAFORM_DIR"; terraform validate
      - run: cd "$TERRAFORM_DIR"; terraform apply -auto-approve -no-color
